name: Total Wellness
favicon: null
layout_spectrum: 0.9436195991002023
typography_spectrum: 0.9967376047279686
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2b29a6'
    - '#5857bb'
    - '#ffffff'
    - '#9192d1'
    - '#b9b7e1'
  brandStrength: 0.625
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 0.261639129370451
purpose: []
