name: Total Wellness
favicon: null
layout_spectrum: 0.9436195991002023
typography_spectrum: 0.9967376047279686
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5947954200673848
  lightness: 0.8316841288469732
  saturation: 0.45991556299850345
  rhythmicContrast: 0.261639129370451
purpose: []
